### ISSUE TITLE
Issues changing User Agent

### ISSUE THREAD

**Issue by Tutunova** [Xewdy444/CF-Clearance-Scraper#7]
Hello, most of the times, when i want to change an user agent, it gets a handshake timeout
This is an example, using the default UA, and using Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

C:\Users\Usuario\Downloads\CFScraperOB2>python main.py -u https://www.petflow.com/ -v
[15:20:52] Checking for cloudflare challenge...
[15:20:52] Cloudflare challenge detected. Fetching cf_clearance cookie...
[15:20:54] Launching headless browser...
[15:20:56] Going to https://www.petflow.com/...
[15:20:57] Solving cloudflare challenge [Managed]...
[15:20:58] Cookie: cf_clearance=ey4oPPQnPTDdZ6LHuC3tg_BiVHJV.BTJCsiUHt7TG78-1668882058-0-150

C:\Users\Usuario\Downloads\CFScraperOB2>python main.py -u https://www.petflow.com/ -v
[15:35:19] Checking for cloudflare challenge...
[15:35:34] _ssl.c:1108: The handshake operation timed out

**Comment by Xewdy444** [comment]
![image](https://user-images.githubusercontent.com/95155966/202870899-cf708200-ce02-45ab-a5d0-74fce1290ab4.png)
It appears that this issue is specific to managed challenges with chrome user agents.

The first solve in the picture used this user agent:
`Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko)`

The second solve in the picture used this user agent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0`

The third solve attempt in the picture used the user agent you provided:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`

As of now, I don't believe I can solve this issue. Cloudflare may just be behaving more aggressive towards requests using chrome user agents. I would recommend using a different user agent in order to solve this cloudflare challenge.
